---
title: "P8105"
author: "Jiawen Zhao"
date: "11/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
library(patchwork)
library(gridExtra)
```

#### Problem 2
```{r}
homicide <- read.csv("./data/homicide-data.csv")%>% 
  na.omit() %>% 
  unite(city_state, c(city,state),sep = ", ") %>% 
  mutate(solved = case_when(grepl("Closed", disposition)==TRUE ~ 1,
  grepl("Closed", disposition)==FALSE ~ 0)) %>% 
  mutate(unsolved = case_when(grepl("Open", disposition)==TRUE ~ 1,
  grepl("Open", disposition)==FALSE ~ 0)) 
homicide_summary = group_by(homicide,city_state) %>% 
  summarise(total_solved = sum(solved),
            total_unsolved = sum(unsolved))
BMD = filter(homicide_summary,city_state=="Baltimore, MD")
result = prop.test(BMD$total_unsolved, BMD$total_solved+BMD$total_unsolved)
broom::tidy(result)

prop_test_results = function(x,n) {
  result = prop.test(x, n)
  broom::tidy(result)
}



sim_results_df = 
  homicide_summary %>% 
  mutate(
    estimate_df = 
      map2(.x = total_unsolved, .y = total_solved+total_unsolved, ~prop_test_results(x = .x, n = .y))
  ) %>% 
  unnest(estimate_df)
  

sim_results_df %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2)+
  scale_x_discrete(guide = guide_axis(angle = 90))+
  geom_point()
```


# Problem 3

```{r}
sim_mean_sd = function(n = 30, mu, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  result = t.test(sim_data$x)
  result = broom::tidy(result)
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      p_value = result$p.value
    )
}
output = vector("list", 500)

t = tibble(mu = c(1,2,3,4,5,6))%>%
  mutate(count = c(500)) %>%
  uncount(count)%>% 
  mutate(estimate_df = map(.x = mu, ~sim_mean_sd(mu = .x))) %>% 
  unnest(estimate_df) %>% 
  mutate(reject = case_when(p_value <= 0.05 ~ 1,
  p_value > 0.05 ~ 0)) 
tp = t %>% group_by(mu) %>% 
  summarise(power = sum(reject)/500)%>% 
  ggplot(aes(x = mu, y = power))+ 
  geom_bar(stat="identity")

reject_t = t%>%
  filter(reject == 1) 

plot1 = t%>% 
  ggplot(aes(x = mu, y = mu_hat))+
  geom_point()


plot2 = reject_t%>% 
  ggplot(aes(x = mu, y = mu_hat))+
  geom_point()
  

grid.arrange(plot1, plot2, ncol=2)


```

# No, their means are not the same.



